### ISSUE TITLE
Does not work with WSL

### ISSUE THREAD

**Issue by The-Noah** [cppshane/Background-Terminal#3]
![image](https://user-images.githubusercontent.com/35819660/76883227-ca0d6c00-6849-11ea-96c4-6871495bfee7.png)

**Comment by cppshane** [comment]
The problem here is that windows and Linux use different newline characters. To fix this I just implemented a command to manually set the newline character that is being sent when you press return. The command can be used to change to a Linux newline character as follows:

`bgt newline \n`

cd2e7fc1506a4c1ba98ba6c0a654085f676671d1

**Comment by The-Noah** [comment]
Running `bgt newline \n` just gives an error of `bgt: command not found`. It would also be nice if you could make it detect of the user runs a command to get into WSL (`bash`, `wsl`, `ubuntu`, etc) and auto set the newline character.

**Comment by cppshane** [comment]
Are you sure you rebuilt the project with the changes..? If the inputted string starts with "bgt" it won't even send the command to cmd.exe, so it definitely shouldn't be outputting that.

Anyway, I was thinking something along the lines of that as well. I was going to just add a menu for users to define trigger commands (bash, wsl, ubuntu, etc.) with their respective newline definitions.
